# Generated by Django 4.0.6 on 2022-07-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='mainphot',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
