# Generated by Django 3.2.14 on 2022-07-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_mainphot_post_mainphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_w', models.CharField(choices=[('PYTHON/DJANGO', 'python/django'), ('JAVA/SPRING', 'java/spring'), ('ANDROID', 'android'), ('ML', 'ml'), ('ETC', 'etc')], max_length=200)),
            ],
        ),
    ]
