# Generated by Django 3.2.14 on 2022-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220729_0234'),
    ]

    operations = [
        migrations.DeleteModel(
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PYTHON/DJANGO', 'python/django'), ('JAVA/SPRING', 'java/spring'), ('ANDROID', 'android'), ('ML', 'ml'), ('PS', 'ps'), ('ETC', 'etc')], default='etc', max_length=200),
        ),
    ]
