# Generated by Django 3.2.8 on 2022-07-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220730_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='myinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=100)),
                ('workExperience', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=100),
        ),
    ]
