# Generated by Django 3.2.14 on 2022-08-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20220801_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hits',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PYTHON/DJANGO', 'python/django'), ('JAVA/SPRING', 'java/spring'), ('ANDROID', 'android'), ('ML', 'ml'), ('PS', 'ps'), ('ETC', 'etc')], default='etc', max_length=200, verbose_name='글 분류'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='post',
            name='postname',
            field=models.CharField(max_length=100, verbose_name='제목'),
        ),
    ]
