# Generated by Django 3.2.14 on 2022-08-03 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220803_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='passwd',
            field=models.CharField(default='', max_length=50, verbose_name='비밀번호'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.CharField(default='borikong', max_length=20, verbose_name='작성자'),
        ),
    ]
