# Generated by Django 3.2.14 on 2022-08-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20220803_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PYTHON/DJANGO', 'python/django'), ('JAVA/SPRING', 'java/spring'), ('ANDROID', 'android'), ('ML', 'ml'), ('PS', 'ps'), ('GUEST', 'guest'), ('ETC', 'etc')], default='etc', max_length=200, verbose_name='글 분류'),
        ),
    ]
